language: java

jdk:
  - openjdk17

branches:
  only:
  - main
  - development

before_script:
  - ls -la

script:
  - mvn clean package jacoco:report

after_success:
  - echo "Process terminated successfully!"
